proc return_bool*() :bool {.importc:"return_bool", cdecl, header:"header.h".}
proc return_char*() :cchar {.importc:"return_char", cdecl, header:"header.h".}
proc return_short*() :cshort {.importc:"return_short", cdecl, header:"header.h".}
proc return_int*() :cint {.importc:"return_int", cdecl, header:"header.h".}
proc return_long*() :clong {.importc:"return_long", cdecl, header:"header.h".}
proc return_float*() :cfloat {.importc:"return_float", cdecl, header:"header.h".}
proc return_double*() :cdouble {.importc:"return_double", cdecl, header:"header.h".}
proc return_uint*() :cuint {.importc:"return_uint", cdecl, header:"header.h".}
proc return_void_ptr*() :pointer {.importc:"return_void_ptr", cdecl, header:"header.h".}
proc return_string*() :cstring {.importc:"return_string", cdecl, header:"header.h".}
proc take_bool*(b :bool) {.importc:"take_bool", cdecl, header:"header.h".}
proc take_char*(c :cchar) {.importc:"take_char", cdecl, header:"header.h".}
proc take_short*(s :cshort) {.importc:"take_short", cdecl, header:"header.h".}
proc take_int*(i :cint) {.importc:"take_int", cdecl, header:"header.h".}
proc take_long*(l :clong) {.importc:"take_long", cdecl, header:"header.h".}
proc take_float*(f :cfloat) {.importc:"take_float", cdecl, header:"header.h".}
proc take_double*(d :cdouble) {.importc:"take_double", cdecl, header:"header.h".}
proc take_uint*(u :cuint) {.importc:"take_uint", cdecl, header:"header.h".}
proc take_pointer*(p :pointer) {.importc:"take_pointer", cdecl, header:"header.h".}
proc take_string*(s :cstring) {.importc:"take_string", cdecl, header:"header.h".}
proc return_int8*() :int8 {.importc:"return_int8", cdecl, header:"header.h".}
proc return_int16*() :int16 {.importc:"return_int16", cdecl, header:"header.h".}
proc return_int32*() :int32 {.importc:"return_int32", cdecl, header:"header.h".}
proc return_int64*() :int64 {.importc:"return_int64", cdecl, header:"header.h".}
proc return_uint8*() :uint8 {.importc:"return_uint8", cdecl, header:"header.h".}
proc return_uint16*() :uint16 {.importc:"return_uint16", cdecl, header:"header.h".}
proc return_uint32*() :uint32 {.importc:"return_uint32", cdecl, header:"header.h".}
proc return_uint64*() :uint64 {.importc:"return_uint64", cdecl, header:"header.h".}
proc return_size*() :csize_t {.importc:"return_size", cdecl, header:"header.h".}
proc take_int8*(v :int8) {.importc:"take_int8", cdecl, header:"header.h".}
proc take_int16*(v :int16) {.importc:"take_int16", cdecl, header:"header.h".}
proc take_int32*(v :int32) {.importc:"take_int32", cdecl, header:"header.h".}
proc take_int64*(v :int64) {.importc:"take_int64", cdecl, header:"header.h".}
proc take_uint8*(v :uint8) {.importc:"take_uint8", cdecl, header:"header.h".}
proc take_uint16*(v :uint16) {.importc:"take_uint16", cdecl, header:"header.h".}
proc take_uint32*(v :uint32) {.importc:"take_uint32", cdecl, header:"header.h".}
proc take_uint64*(v :uint64) {.importc:"take_uint64", cdecl, header:"header.h".}
proc take_size*(v :csize_t) {.importc:"take_size", cdecl, header:"header.h".}
