import bindings

let rb: bool      = return_bool()
let rc: cchar     = return_char()
let rs: cshort    = return_short()
let ri: cint      = return_int()
let rl: clong     = return_long()
let rf: cfloat    = return_float()
let rd: cdouble   = return_double()
let ru: cuint     = return_uint()
let rp: pointer   = return_void_ptr()
let rstr: cstring = return_string()

take_bool(rb)
take_char(rc)
take_short(rs)
take_int(ri)
take_long(rl)
take_float(rf)
take_double(rd)
take_uint(ru)
take_pointer(rp)
take_string(rstr)

let ri8: int8    = return_int8()
let ri16: int16  = return_int16()
let ri32: int32  = return_int32()
let ri64: int64  = return_int64()
let ru8: uint8   = return_uint8()
let ru16: uint16 = return_uint16()
let ru32: uint32 = return_uint32()
let ru64: uint64 = return_uint64()
let rsz: csize_t = return_size()

take_int8(ri8)
take_int16(ri16)
take_int32(ri32)
take_int64(ri64)
take_uint8(ru8)
take_uint16(ru16)
take_uint32(ru32)
take_uint64(ru64)
take_size(rsz)

